### ISSUE TITLE
Allow updating server from UI

### ISSUE THREAD

**Issue by jjcf89** [mroote/factorio-server-manager#10]
Moving this to its own issue.
The updater script could be used for reference.
https://github.com/narc0tiq/factorio-updater

**Comment by TechnoNerdDad** [comment]
I second this motion...

**Comment by sean-callahan** [comment]
Currently working on this.

**Comment by dgw** [comment]
If updating on manual command from a FSM admin, activity detection is likely not a requirement for initial implementation.

Later, such a feature could be added. Also, notifying the players in-game through RCon and giving them some configurable amount of time to find a stopping point would be a nice enhancement.

**Comment by knoxfighter** [comment]
A helpful link, where the update is done with the command-line: https://forums.factorio.com/viewtopic.php?t=14395

**Comment by knoxfighter** [comment]
Implemented with #179

**Comment by Bykow** [comment]
Hey, any news regarding this feature ?

**Comment by Pan-Bubr** [comment]
Hello, any updates? 😢

**Comment by jannaahs** [comment]
Nope, nothing has changed. We will post an update here, if there is any progress.

**Comment by llann** [comment]
Waiting there is something integrated in factorio-server-manager you can use https://github.com/Bisa/factorio-init on your server and use it just to update factorio (you can do more but then you start to have some features overlap with factorio-server-manager).

Then to update you can simply run `factorio update` :)

Maybe something that could be included in this project as it's "just" a shell script, but I understand that it is never easy to integrate other tools.

**Comment by knoxfighter** [comment]
Something like that is already included in the docker image. If you use our docker image, you can simply restart it and the newest version of factorio is downloaded (depending on the `FACTORIO_VERSION` env variable).

**Comment by llann** [comment]
Ok nice :)

I'm only using docker to dev not to host services, but thanks for the info :) Could be cool to integrate something in the non docker install. But I completly understand how it's not in your top priorities ;)

**Comment by knoxfighter** [comment]
Command line argument to apply a patch (downloadable from wube): `--apply-update arg`

**Comment by Eurymachus** [comment]
Greetings! Is there anyway to update from the Manager yet? I noticed there wasn't an update for some time.

How can I do it otherwise?

**Comment by knoxfighter** [comment]
Restart the docker container, it contains an update mechanism

**Comment by Eurymachus** [comment]
Running on linux not docker :D

**Comment by knoxfighter** [comment]
Then you have to update manually or use one of the update scripts, that exist. (Make sure the addon manager is turned off while doing so).

**Comment by Eurymachus** [comment]
Alrighty! Looking forward to when this is added into the manger! \o/
