### ISSUE TITLE
The settings can not be changed to FALSE

### ISSUE THREAD

**Issue by marcin212** [mroote/factorio-server-manager#101]
It is always true:
https://github.com/mroote/factorio-server-manager/blob/71050f8d726b05b080709ee222e5c524efbd7915/ui/App/components/ConfigContent.jsx#L45

![js-boolean-test](https://img.bymarcin.com/2018-05-03_21-04-49_1L167sIpIEDsWRWu.png)

**Comment by mroote** [comment]
Woops that's Javascript :P You are totally correct, I'll have to fix the form up.

**Comment by ShinoHarvest** [comment]
not fixed on window 0.7.2

**Comment by sean-callahan** [comment]
This has been fixed with #110 and can be closed.
