### ISSUE TITLE
crash server & manager just for warning

### ISSUE THREAD

**Issue by ShinoHarvest** [mroote/factorio-server-manager#104]
on window
if make warning / fake error during server start server & manager crash, but without server manager all work this make you manager totaly uslessfull

+ you manager no use factorio config.ini impossible strat server on other port of default

**Comment by knoxfighter** [comment]
This is not a valid issue. It has no information about any issue or any logs or error descriptions.
If there is any error here, please reopen this issue and explain what happens and add logs.
