### ISSUE TITLE
try build on w7

### ISSUE THREAD

**Issue by ShinoHarvest** [mroote/factorio-server-manager#105]
<....>managerer-master\src>go build
warning: GOPATH set to GOROOT (J:\Go\) has no effect
mod_Mods.go:10:2: cannot find package "lockfile" in any of:
        J:\Go\src\lockfile (from $GOROOT)
        ($GOPATH not set)

**Comment by knoxfighter** [comment]
You did the same mistake as me. You need to add a GO-Directory into the GOPATH. In this Directory you add a src folder. and in this folder you have folders for each project you have.
For me the project folder is: `/GO/src/factorio-server-manager/manager` and in my GOPATH i wrote `/GO/`

**Comment by ShinoHarvest** [comment]
GOPATH = J:\Go

J:\Go\src\factorio-server-manager-master\src>go build
warning: GOPATH set to GOROOT (J:\Go\) has no effect
can't load package: J:\Go\src\factorio-server-manager-master\src\auth.go:7:2: no
n-standard import "github.com/apexskier/httpauth" in standard package "factorio-
server-manager-master/src"

**Comment by knoxfighter** [comment]
you need to install things first, like defined in the readme

**Comment by ShinoHarvest** [comment]
already instaled after try i have look this https://medium.freecodecamp.org/setting-up-go-programming-language-on-windows-f02c8c14e2f
specify GOPATH = workspace and no go instal dir
change GOPATH = J:\Go-Workspace
reinstall dependance and it go in J:\Go-Workspace
mv manager to J:\Go-Workspace\src\factorio-server-manager-master\src
but
J:\Go-Workspace\src\factorio-server-manager-master\src>go build
# factorio-server-manager-master/src
.\mods_handler.go:444: undefined: http.StatusLocked

**Comment by knoxfighter** [comment]
Which Go version do you use?

**Comment by ShinoHarvest** [comment]
```
J:\Go-Workspace\src\factorio-server-manager-master\src>go version
go version go1.6 windows/amd64
```
downloaded with link in wiki section

**Comment by knoxfighter** [comment]
ok, you cant use version 1.6 anymore. I've used StatusLocked (http-statuscode 423) which was added in 1.7
Please install a newer GoLang-Version

**Comment by ShinoHarvest** [comment]
ok thx i try this tomorow, need probaly change wiki for dl link & GOPATH = workspace for escape warning

**Comment by ShinoHarvest** [comment]
new prob >_< 

> J:\Go-Workspace\src\factorio-server-manager-master>npm install
> npm ERR! install Couldn't read dependencies
> npm ERR! Windows_NT 6.1.7601
> npm ERR! argv "J:\\Program Files\\nodejs\\node.exe" "J:\\Program Files\\no
> node_modules\\npm\\bin\\npm-cli.js" "install"
> npm ERR! node v4.2.6
> npm ERR! npm  v2.14.12
> npm ERR! path J:\Go-Workspace\src\factorio-server-manager-master\package.j
> npm ERR! code ENOPACKAGEJSON
> npm ERR! errno -4058
> npm ERR! syscall open
> 
> npm ERR! package.json ENOENT: no such file or directory, open 'J:\Go-Works
> rc\factorio-server-manager-master\package.json'
> npm ERR! package.json This is most likely not a problem with npm itself.
> npm ERR! package.json npm can't find a package.json file in your current d
> ry.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     J:\Go-Workspace\src\factorio-server-manager-master\npm-debug.

**Comment by knoxfighter** [comment]
Closed due to age
