### ISSUE TITLE
Go build not working

### ISSUE THREAD

**Issue by IeuanK** [mroote/factorio-server-manager#111]
```root@factorio:/opt/factorio-server-manager# make
Installing Packages
Building Backend - Linux
src/mod_Mods.go:10:2: cannot find package "lockfile" in any of:
        /usr/lib/go-1.7/src/lockfile (from $GOROOT)
        /root/go/src/lockfile (from $GOPATH)
Makefile:28: recipe for target 'factorio-server-manager-linux' failed
make: *** [factorio-server-manager-linux] Error 1
``` 

I attempted to use the current release of the panel, which does not appear to be functional (simply causes a crash). Wanted to try build it myself, but even after manually installing all Go dependencies I get this error.

Gopath is set to `$HOME/go`, cloned repo is in `/opt/factorio-server-manager`

What am I missing/doing wrong?

**Comment by knoxfighter** [comment]
Oh, this again, i wrote about this issue in #105 already :)
>You did the same mistake as me. You need to add a GO-Directory into the GOPATH. In this Directory you add a src folder. and in this folder you have folders for each project you have.
>For me the project folder is: /GO/src/factorio-server-manager/manager and in my GOPATH i wrote /GO

**Comment by IeuanK** [comment]
So to clarify, would that mean that I need my `/opt/factorio-server-manager` changed to `/opt/go/src/factorio-server-manager` and then add `/opt/go` to my gopath?

**Comment by knoxfighter** [comment]
yes. If it still doesn't work, just answer again :)
