### ISSUE TITLE
Feature Request: Add the ability to specify factorio boot arguments

### ISSUE THREAD

**Issue by Thorlon1** [mroote/factorio-server-manager#125]
Because of Centos 7 not having 2.18 glib I have to specify the boot path for factorio like so 

/opt/glibc-2.18/lib/ld-2.18.so --library-path /opt/glibc-2.18/lib ./bin/x64/factorio --start-server-load-latest --executable-path ./bin/x64/factorio

Possible to add this? 

Cheers

**Comment by Psychomantis71** [comment]
I have the same issue with my server, I really can't see the logic begind the decision to use a version of glibc that is not supported by CentOS 7 / RHEL, almost everybody uses those operating systems for their servers. Anyways, I'd like to ask for the same. I'll inspect the code myself this week and see if I can perhaps do something about it, but no promises, I'm just a rookie.

**Comment by Psychomantis71** [comment]
Hey, I finally had some free time and found a solution. I made a fork of the project and published a new release with the added parameters for the usage of custom glibc.
I also made a pull request so I hope it will be merged soon.

Cheers

**Comment by Thorlon1** [comment]
https://github.com/mroote/factorio-server-manager/pull/155 Fixed by this.
