### ISSUE TITLE
Server manager docker container displays a blank page since update

### ISSUE THREAD

**Issue by danstis** [mroote/factorio-server-manager#134]
After the latest release I am getting a blank page when opening the Server Manager URL.
I am using the docker container version, and have tested with a new clean container instance.

This is what I see on the main page:
![image](https://user-images.githubusercontent.com/2137928/53541489-d0a94280-3b65-11e9-9929-5bfd907f60a6.png)

This is logged in the console:
![image](https://user-images.githubusercontent.com/2137928/53541440-9770d280-3b65-11e9-99e2-48d73f954bf3.png)

**Comment by smoopmeister** [comment]
Confirming i'm also getting the same error on the windows release

**Comment by mroote** [comment]
Hmm sorry about that I seem to be getting the same error. I checked the error in development mode and it appears to be an error due to routing? @knoxfighter maybe you have an idea? I haven't made a build in a bit so I'm not sure if it's something on my end.

**Comment by knoxfighter** [comment]
I currently am fixing this problem. Its not that easy to find and fix, will take a few more hours :)

**Comment by knoxfighter** [comment]
PR is open. The login-page has styling problems, but should work now :)

**Comment by Najsr** [comment]
@knoxfighter Could you please make a temporary build before PR is merged and new released published? 
Thanks.

**Comment by knoxfighter** [comment]
@Najsr I created a temporary release: https://github.com/knoxfighter/factorio-server-manager/releases/tag/0.8.1.rc1
I cannot update the release on the docker hub.

**Comment by keckrich** [comment]
The new release did not fix the white page issue for me.

**Comment by knoxfighter** [comment]
The Linux release i created is fixed for me. Be careful: **I didn't updated the docker images!**

**Comment by tardisx** [comment]
> The new release did not fix the white page issue for me.

Agreed. Still white screen for me with that release.

If I use incognito mode, I do see a login screen. So presumably something from the cookie state is breaking things. I suspect clearing cookies will fix that.

**Comment by Najsr** [comment]
@knoxfighter I don't use linux and it works now. Thanks!

**Comment by mroote** [comment]
I've merged in @knoxfighter's fix and updated the docker container for 0.8.1. Thanks for confirming @Najsr!

**Comment by knoxfighter** [comment]
@mroote thanks for fixing it completly, for some reason, this error did not occure on my side :(
