### ISSUE TITLE
allow_commands in server-settings is a string, not a boolean 

### ISSUE THREAD

**Issue by tardisx** [mroote/factorio-server-manager#139]
I feel like this is a factorio change, but I cannot see it in the changelog. 

The factorio server manager dropdown only allows true or false, but the example file and comment indicates it is a string with three possible values. 

Writing out a boolean prevents the server from starting. 

I am using 0.17.7 and the latest factorio server manager.

**Comment by knoxfighter** [comment]
You're right, it has three possible value: true, false and "admin-only".

>   "_comment_allow_commands": "possible values are, true, false and admins-only",
 "allow_commands": "admins-only",
Source: https://github.com/GameServerManagers/Game-Server-Configs/blob/master/Factorio/server-settings.json

**Comment by knoxfighter** [comment]
merged into develop, will be included in the next release
