### ISSUE TITLE
Cannot change factorio server port

### ISSUE THREAD

**Issue by justindude521** [mroote/factorio-server-manager#141]
Port does not changed based off of config.ini. Will show correct port in settings but upon starting server will use default port 34197

**Comment by knoxfighter** [comment]
The server-manager does start factorio with sepcific command prameters. Also the paramter --port is used, which overrides, what is written in the factorios config.ini.
To change the port, where factorio starts on, click on "Advanced" in the server-manager, there you can specify the ip-adress and the port.
