### ISSUE TITLE
Admins no longer stored in server-settings.json

### ISSUE THREAD

**Issue by DanielNagy** [mroote/factorio-server-manager#151]
admin(s) auto-promote is not working with 0.17 factorio, and upon further investigation, it appears that the admins list is no longer part of the server-settings.json file but rather a separate file server-adminlist.json file.

So, you need to, create a server-adminslist.json file in the same array format as current. and update that from the GUI.

When starting factorio add the arg --server-adminlist referencing the new file in "config.FactorioConfigDir". otherwise, factorio will default to look for server-adminlist.json file in /opt/factorio (which is not ideal when used in a docker configuration and the config folder is mapped local system)

References below to details required.

https://wiki.factorio.com/Multiplayer
To give yourself admin access, you need to create a server-adminlist.json in the same directory as factorio-current.log. The file should contain a list of admins, like so: [ "user1", "user2" ]

https://wiki.factorio.com/Console#Command_line_parameters
--server-adminlist FILE | Path to file with server adminlist.

**Comment by DanielNagy** [comment]
Also i discovered that factorio_server.go has the Factorio Run "args" are referencing a hard coded "server-settings.json" string, rather than config.SettingsFile

`"--server-settings", filepath.Join(config.FactorioConfigDir, "server-settings.json"),`

**Comment by DanielNagy** [comment]
This change happened in 0.17.0
https://wiki.factorio.com/Version_history/0.17.0

`Added server-adminlist that's used to determine which people are admins when hosting any multiplayer game. This is synced both ways when hosting any game.`

`Removed "admins" from the multiplayer server-settings file - they're now handled through server-adminlist.`

**Comment by knoxfighter** [comment]
Thats explains, why i had problems with making myself admin on my server xD

**Comment by DanielNagy** [comment]
prob should call it FactorioAdminList not FactorioAdminFile 
:)

**Comment by DanielNagy** [comment]
@knoxfighter the server-adminlist.json file if placed in the config folder, needs to be referenced at startup by the --server-adminlist arg

I'd say you'd need to version check also, to only apply the --server-adminlist arg to 0.17 only
or else you have to place the server-adminlist.json file in the /opt/factorio folder, which isnt ideal for docker configuration.

**Comment by knoxfighter** [comment]
Your right, i overlooked that. I implemented it and also moved the file in the config directory :)

You can also write comments directly under the Pull Requests xD

**Comment by knoxfighter** [comment]
Merged into develop, will be fixed with the next release.
