### ISSUE TITLE
can't update server in docker

### ISSUE THREAD

**Issue by ghost** [mroote/factorio-server-manager#160]
because of the fact, that the linux version tells me "file not found" at this command `./factorio-server-manager --dir <path to factorio server>`
I tried the docker version, but this is only factorio version 0.17.3-0. Is there a possibility to update the factorio server to the latest experimental inside the docker container?

**Comment by TheFox1312** [comment]
nvm.. found the readme in the docker folder.. sorry for this issue

**Comment by TheFox1312** [comment]
okay found the issue here. I added the latest version into the dockerfile but it changes nothing. I also tried to manually enter the complete link into the dockerfile to the latest headless server download but it catches the 0.17.3 instead of the 0.17.66

**Comment by organsnyder** [comment]
I was able to build an image with the latest Factorio version by cloning the repo and running a docker build (as described in the readme).

**Comment by knoxfighter** [comment]
Closed due to age, also further things like autoupdating from inside the server-manager have additional issues.
