### ISSUE TITLE
Unable to launch the server manager

### ISSUE THREAD

**Issue by Najsr** [mroote/factorio-server-manager#161]
Hello there, I have a problem with latest version of this factorio server manager (version 0.8.2)
I am running Debian 9 `Linux myserver 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u5 (2019-08-11) x86_64 GNU/Linux`
When I try to run the executable all I get it this message:
```
factorio@myserver:/home/factorio/factorio-web# ./factorio-server-manager
bash: ./factorio-server-manager: No such file or directory
```
Is there any solution for this?
Thanks

**Comment by knoxfighter** [comment]
Do you have all needed files extracted and placed next to the binary?
Be sure, your in the correct directory. The released zip-files containing a root-directory, which is also named `factorio-server-manager`

**Comment by forleong** [comment]
Same here, but I can start the server with 0.8.1 version
Just 0.8.2 release is not working

**Comment by ideaman924** [comment]
Not working on Ubuntu Server 18.04 LTS. Downloaded and unzipped, but bash returns "No such file or directory." This is a clean install on a DigitalOcean VPS.

**Comment by hyper1on** [comment]
Hi, I'd like to mention that the 0.8.2 release is still up.  I've been effing around with it trying to get it to run until I saw this post about it being broken.

**Comment by knoxfighter** [comment]
This is a new 0.8.2 Release, it is created only a month ago and should work fine. So your error has a different reason.
Can you please sent more information about the error, so we can look into it and fix it.
The best thing would be, to do it in a new issue with yur log ouput :smile:

**Comment by hyper1on** [comment]
Ah, okay.  I had the same issue, no such file or directory.  0.8.1 ran with no issues for me.

**Comment by knoxfighter** [comment]
- Your Output of the command (with the "no such file or directory error")
- Your operating system, distribution and version.
- A hash of the zip or factorio-server-manager executable

**Comment by hyper1on** [comment]
c9d8edcb86779a742c598f8667affa04  factorio-server-manager-linux-0.8.2.zip
Linux SERVERNAME 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

USER@SERVER:/home/factorio/FSM/factorio-server-manager$ sudo ./factorio-server-manager --dir /home/factorio/factorio/
sudo: unable to execute ./factorio-server-manager: No such file or directory

Sorry it took me a little while.  I was hesitant to fool with something that was working, but I needed to update factorio so I decided to give it a shot.  Is there something I am doing wrong?

**Comment by knoxfighter** [comment]
For tracking and to help my brain:
The binary created with travis is build against musl-libc instead of glibc.
```
ldd factorio-server-manager 
	linux-vdso.so.1 (0x00007ffecd12f000)
	libc.musl-x86_64.so.1 => not found
```

When compiling on my local machine:
```
ldd factorio_server_manager_17 
	linux-vdso.so.1 (0x00007ffdb2981000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb3cff56000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb3cfb65000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb3d0175000)
```

**Comment by knoxfighter** [comment]
The old build was generated with alpine linux, which uses musl-libc instead of glibc.
This can be useful, when running in a docker-container, but in most cases, glibc is installed, and the other build is not needed.

I replaced the old build, so download the 0.8.2 Release again and it should work.

**Comment by hyper1on** [comment]
Same issue as far as I can tell.  Here is a screenshot of what I could find installed related to glib:
http://prntscr.com/r2iyng

c48e13f1e0bcbeb7cfd8e729868db469  factorio-server-manager

Linux SERVERNAME 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

USER@SERVER:/home/factorio/FSM/factorio-server-manager$ ./factorio-server-manager
-bash: ./factorio-server-manager: No such file or directory

**Comment by knoxfighter** [comment]
You use ubuntu, so you have no additional dependency to install. The only dependency golang is linked against, is glibc and that is included in ubuntu.

I noticed, that the md5 hash you sent, is not the one i have, when downloading the zip and unpack it. 
Please download the zip again and unpack and override the previous files (that is correctly linked).


Just for your information, how to get the correct error message:
To check, what exactly the error means, you can run `ldd`.
In my case, the ldd output shows, that it is using glibc:
```
ldd factorio-server-manager 
	linux-vdso.so.1 (0x00007ffebd244000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fec83c29000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fec83838000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fec83e48000)
```

And, in case, when it is not finding a dependency (on my system no musl-libc is installed):
```
ldd factorio-server-manager 
	linux-vdso.so.1 (0x00007ffecd12f000)
	libc.musl-x86_64.so.1 => not found
```

**Comment by hyper1on** [comment]
Hey, looks like it's working!  I had two zip files with the 0.8.2 version in my directory so I must have unzipped the old one (it's deleted now).  Thank you for your patience with me :)

**Comment by knoxfighter** [comment]
Good thing, thats out of the world now and with #170 this shouldn't be a problem in the future :)

Thanks for reporting.
