### ISSUE TITLE
Unused original files in /data

### ISSUE THREAD

**Issue by GhislainOlitec** [mroote/factorio-server-manager#173]
Software at the top! But I have a quick question

Is it normal that when I launch FSM the server files /factorio/data/server-settings.json and /factorio/server-adminlist.json be created in /factorio/config?

The Factorio server originally uses /data/server-settings.json or server-settings-example.json and suddenly FSM gives me unconfigured files. Why not use the original files directly?

I missed a configuration in my command line?

Server 0.18.17: /home/user/factorio
FSM: / home/user/fsm
Command in the FSM folder: ./factorio-server-manager --dir /home/user/factorio

I did not find information on the other issues except #59 but in my config.ini file of FSM it is well marked
`"settings_file": "server-settings.json",`

**Comment by knoxfighter** [comment]
Factorio is not loading the configs from `__factorio__/data/` by default! By default the config files for factorio are loaded from `__factorio__/config/`. This setting can be changed in the `__factorio__/config-path.cfg`.
Currently changing the configs directory in FSM is not supported.

**Comment by GhislainOlitec** [comment]
Ok so this should just be a change between a Headless server and a Server with the game. Because by reading the [Wiki](https://wiki.factorio.com/Multiplayer#How_to_list_a_server-hosted_game_on_the_matching_server) I have the files in /data

At least the problem is solved ;)

**Comment by knoxfighter** [comment]
That is true, but you have to define the `--server-settings` parameter, when starting factorio. The FSM is doing this and setting the value to the config directory^^
`--server-settings = filepath.Join(config.FactorioConfigDir, config.SettingsFile)`
