### ISSUE TITLE
Could not create modpack directory

### ISSUE THREAD

**Issue by MogliDerZauberKoenig** [mroote/factorio-server-manager#65]
Hello,
when i start the server with this command: 
./factorio-server-manager --dir /opt/factorio-community/.factorio

it shows this error:
2017/01/15 19:00:46 Could not create modpacks directory: mkdir /opt/factorio-community/.factorio/modpacks: no such file or directory
2017/01/15 19:00:46 error opening log file: open /opt/factorio-community/.factorio/factorio-server-manager.log: no such file or directory

Can you please help me?

**Comment by OnkelDom** [comment]
The user has no read/write permission to the folder?!

**Comment by MajorMJR** [comment]
Does the /opt/factorio-community/.factorio directory exist and have read and write permissions for the Factorio user?

**Comment by MogliDerZauberKoenig** [comment]
Thanks i forgot to give the user the permissions

**Comment by mroote** [comment]
Glad to hear it, cheers
