### ISSUE TITLE
Specify server ip

### ISSUE THREAD

**Issue by goldmorphin** [mroote/factorio-server-manager#79]
Hello!

I can't find how i can specify server bind address, certainly for game server not web server.
Or it's not possible?

**Comment by mroote** [comment]
Hi @goldmorphin 

You can specify the the bind address with the '--host' flag when launching the server manager.  By default it listens on all addresses (0.0.0.0) but you can specify any address to listen on.

**Comment by goldmorphin** [comment]
It's for webserver, not game.
I would like to bind webserver on local ip, but game server bind on public ip.

**Comment by mroote** [comment]
Oh I see what you mean, this feature doesn't currently exist but it would be a useful feature to add for sure.  I'll look into adding this into the next release.

**Comment by goldmorphin** [comment]
Thank you so much! <3

**Comment by goldmorphin** [comment]
Bump! :(

**Comment by mroote** [comment]
I've finally added this in v0.6.1.

**Comment by goldmorphin** [comment]
Hi!
What's the flags for binding?
--host it's for webserver, right?
How i can specify IP for game (factorio) server in this case?

**Comment by mroote** [comment]
You can use the -game-bind-address.  Like this: `-game-bind-address 0.0.0.0`

**Comment by mroote** [comment]
You can also just choose the IP to bind to in the web UI.
