### ISSUE TITLE
Use standalone docker containers for running server instances

### ISSUE THREAD

**Issue by SvenssonWeb** [mroote/factorio-server-manager#81]
There exists many good containers for factorio.
Together with early issue #3 it would remove the need to install an instance on the target system.
Factorio SM could just be provided with the target version when triggering the creation.

**Comment by mroote** [comment]
It would be nice to have the two components in separate containers but there are pretty closely tied together at the moment.  

Starting and stopping the game server is currently run on the host machine just with shell commands.  This could be modified to support starting a docker container possibly.
