### ISSUE TITLE
Mod selection option

### ISSUE THREAD

**Issue by Djfe** [mroote/factorio-server-manager#82]
just a feature request, in-case someone wants to implement it:
Upload more than one mod at a time (<input multiple>)

and maybe upload mod packs to servers (zip's containing mod zip files) and let the user switch between mod packs by clicking them

Also nice could be activating/deactivating using checkboxes and functionality to read that from the client's jsons files

it probably doesn't make sense to implement all of the above, or at least not in that way
but a combination could be nice

(this functionality is obviously useful for users without terminal access)

**Comment by knoxfighter** [comment]
I am currently implementing some of you're requested things :)
Will be ready in a few weeks. The current status can be seen in my fork

**Comment by mroote** [comment]
Thanks @knoxfighter!  Let me know if you have any questions I could help with

**Comment by Djfe** [comment]
Cool! :)

Another idea:
if you're creating a mod pack on the server, then it would be helpful to be able to enable/disable all of the checkboxes (for mods) at a time instead of one at a time. (Only needs simple javascript afaik)

**Comment by knoxfighter** [comment]
@Djfe Currently its only possible to save the current installed mods as a modpack. The problem is, uploading a modpack could cause inconsistent data.
![Screenshot of current modpack section](https://user-images.githubusercontent.com/18680546/30191705-a15dfaec-947d-11e7-91bf-b7de8b3cf644.png)

Is this enough, or do you want some more functions for it?

**Comment by Djfe** [comment]
yeah,
I'm already greatful, that you took the time to further improve this tool :)

Is it possible now to upload more than one mod (zip file) at a time? (<input [...] multiple>)

**Comment by knoxfighter** [comment]
yup, it is possible :)
And i also build a connection to the ModPortal-API, so you can download mods directly from the ModPortal (mods.factorio.com)
Hopefully it dont break with the ModPortal 2.0 Patch in a few weeks.

**Comment by Djfe** [comment]
nice

do you think the "mod-list.json" would be enough to "define" modpacks?

probably not (mod version, UUID, local mods etc.), but it would be cool, if the server would just pull mods using the dependencies from such a file

But that's probably a feature for the factorio devs to code
They really should add something to the client as well, so that the client automatically adopts itself to the server config. (it downloads the mod-list and then the needed dependencies automatically)

oh, well ^^

**Comment by knoxfighter** [comment]
I'm almost ready, just testing stuff left. Currently only with the possibility to make modpacks out of the current installed mods.
Problem is, the mod-list.json don't have enough information to download it from the mod-portal.
Its a good idea, but i don't have a good idea, how to implement it, so it is easy to use.

**Comment by Djfe** [comment]
Why shouldn't there be enough info?
The api is pretty extensive and the name is unique (afaik) and matches the mod.
https://wiki.factorio.com/Mod_portal_API

https://mods.factorio.com/api/mods/MapLabels

For missing mods:
Just select the newest version from the json reply that fits the installed factorio server version ;)

And if there is a version already then use that one and maybe check whether updates are available.
The user could then decide in the gui to update mod x or all mods.

**Comment by knoxfighter** [comment]
Yes, your write, it's enough info to do that, but it will need a new popup/menu to have this possible for the user.
I will do it in a different Pull-Request, when i find the time :)

The updates are currently already detected and an update-button is available (the update all button currently breaks the whole thing). Actually i dont detect which factorio version is installed, so it will be updated to the newest version the mod is programmed to, i think added this and showing the factorio-version the mod needs is a good idea to do know.
