### ISSUE TITLE
Error parsing mod-list.json

### ISSUE THREAD

**Issue by ghost** [mroote/factorio-server-manager#83]
2017/09/26 15:28:22 Error parsing mod-list.json JSON: json: invalid use of ,string struct tag, trying to unmarshal unquoted value into bool

Not sure if this is due to a change in 0.15.34 or some other problem with the 0.6.0 release of FSM.
Bug causes the Mod Toggle list to be empty.

Linux Ubuntu 16.04
Factorio Headless 0.15.34
FSM 0.6.0 release

**Comment by mroote** [comment]
Hi @anup-ap,

Could you post the mod-list.json file please? Maybe there is a syntax error in the file.

**Comment by anup-ap** [comment]
changed the extension to comply w/ file constraints.
[mod-list.txt](https://github.com/mroote/factorio-server-manager/files/1335184/mod-list.txt)

**Comment by kjablonski** [comment]
i have the same issue.  The server when creating the file for the first time does not put the true in quotes for the base mod.

**Comment by knoxfighter** [comment]
I've rewritten the complete modsection in #84 and in my tests the factorio server itself, also dont add quotes around these boolean values.
Hopefully it is only a bug with the old ModSection and my new Code does it better :)
For me it is working quite well and im using this tool for 2 Servers.

**Comment by knoxfighter** [comment]
Closed due to age and bug seems fixed.
