### ISSUE TITLE
Unable to add admins on the Game Configuration Page

### ISSUE THREAD

**Issue by kjablonski** [mroote/factorio-server-manager#85]
I was trying to add myself as an Admin and after I add my username and restart the server, I get the following error:

 0.000  Error Util.cpp:62: Value must be a list or dictionary in property tree at ROOT.admins
2017/11/27 13:38:20 [0.000 Error Util.cpp:62: Value must be a list or dictionary in property tree at ROOT.admins]

FSM version: 0.6
factorio version: 0.15.37

**Comment by apdjz** [comment]
what commands are you doing and show the game config page

**Comment by Finkregh** [comment]
Same problem here, when i add an admin the generated config contains `"admins": "foo"`, but should contain `"admins": ["foo"]`

**Comment by mroote** [comment]
I can reproduce this issue, I think as a workaround you can just enter the admins value as an array `["admin_user"]`. 

I'm working on fixing a few bugs with the settings form for the next release including this one so hopefully I'll have a fix soon.

**Comment by Finkregh** [comment]
that wont work, as things will be escaped :)

this is also an issue at "Visibility" and "Tags"

**Comment by dgw** [comment]
Yep, noted while trying to get my server up again for 0.16. The settings form likes to force things to string format, even if they look like lists/arrays, so you end up with things like `"admins": [\"username\"]` in the JSON. Having other issues relating to connectivity with Factorio itself, too, which doesn't help testing.

**Comment by shark-net** [comment]
Are there any usable workarounds for this? I can't start a server at all anymore.

**Comment by dgw** [comment]
Edit the server-settings file manually after configuring everything else with the webUI, I guess.

**Comment by shark-net** [comment]
I tried this, but starting the server from the webUI seems to overwrite any manual changes to the config files

**Comment by mroote** [comment]
Sorry for the delay with this bug. I think I have a fix now and have made a new version (0.7.1) which should hopefully fix it.  If you could give that a test and see if it's working for you that would be great.

**Comment by shark-net** [comment]
Oops!! Its working. I Just needed to rebuild the dockerfile with the 0.7.1 env var. Thanks!

**Comment by mroote** [comment]
I've updated the dockerfile with the new version so you can pull the latest container once the build finishes.
