### ISSUE TITLE
issue on debian linux

### ISSUE THREAD

**Issue by Panterh3art** [mroote/factorio-server-manager#93]
troy@vps221680:~/factorio-server-manager$ make gen_release
Building Frontend
npm WARN package.json factorio-mod-manager@0.1.0 No repository field.
npm WARN package.json factorio-mod-manager@0.1.0 No README data

> factorio-mod-manager@0.1.0 build /home/troy/factorio-server-manager/ui
> NODE_ENV=production ./node_modules/webpack/bin/webpack.js --progress --profile --colors

/usr/bin/env: node: No such file or directory

npm ERR! factorio-mod-manager@0.1.0 build: `NODE_ENV=production ./node_modules/webpack/bin/webpack.js --progress --profile --colors`
npm ERR! Exit status 127
npm ERR!
npm ERR! Failed at the factorio-mod-manager@0.1.0 build script.
npm ERR! This is most likely a problem with the factorio-mod-manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production ./node_modules/webpack/bin/webpack.js --progress --profile --colors
npm ERR! You can get their info via:
npm ERR!     npm owner ls factorio-mod-manager
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! cwd /home/troy/factorio-server-manager/ui
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/troy/factorio-server-manager/ui/npm-debug.log
npm ERR! not ok code 0
Makefile:24: recipe for target 'app/bundle.js' failed
make: *** [app/bundle.js] Error 1
troy@vps221680:~/factorio-server-manager$

the directory exists

root@vps221680:~# mkdir /usr/bin/env
mkdir: cannot create directory ‘/usr/bin/env’: File exists
root@vps221680:~#

**Comment by mroote** [comment]
It looks like you don't have node.js installed:

```
/usr/bin/env: node: No such file or directory
```

**Comment by knoxfighter** [comment]
Closed due to age. If the error persist, please reopen this issue or create a new one.
