### ISSUE TITLE
Autostart Factorio Server after start of factorio-server-manager?

### ISSUE THREAD

**Issue by BernhardLinz** [mroote/factorio-server-manager#96]
I am using factorio-server.manager on Ubuntu 16.04. and start the manager with a systemd script - so the the manager will run after a rebbot of the server.

it would be nice if the manager could start the factorio server with the last map.
or i missed the option?

Best Regards,
Bernhard Linz

Here is my example systemd-script:
`[Unit]`
`Description=Factorio Server service`
`After=network.target`
` `
`[Service]`
`Type=simple`
`User=root`
`WorkingDirectory=/home/factorio/factorio-server-manager`
`ExecStart=/home/factorio/factorio-server-manager/factorio-server-manager --dir /home/factorio/factorio/ -port 8008`
`SyslogIdentifier=factorio-SM`
`StandardOutput=syslog`
`StandardError=syslog`
`Restart=always`
`RestartSec=5`
` `
`[Install]`
`WantedBy=multi-user.target`

**Comment by Dergonic** [comment]
I did it anoher way (Starting server manager using Cron & @reboot) but I would LOVE to have my server starting automatically too.

**Comment by Psychomantis71** [comment]
This issue is the same as #107 , posted there a temp fix until we iron out all bugs and merge the autostart feature with the master branch.

**Comment by knoxfighter** [comment]
A feature to autostart factorio after launching FSM was added with #179. This will be released in the next release.
