### ISSUE TITLE
Server start failing

### ISSUE THREAD

**Issue by Seorii** [mroote/factorio-server-manager#97]
This is the error it exits with. I can confirm that the server starts if I just manually start w/o this server manager. 

2018/03/18 12:50:29 Factorio Server:   ["layer 191"] = "lab-white",
2018/03/18 12:50:29 Factorio Server:   ["layer 192"] = "tutorial-grid"
2018/03/18 12:50:29 Factorio Server: }
panic: runtime error: index out of range

goroutine 174 [running]:
main.(*FactorioServer).parseRunningCommand(0xc42010a000, 0xa45920, 0xc420217770, 0xc420585b80, 0xa)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/factorio_server.go:176 +0x6a5
created by main.(*FactorioServer).Run
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/factorio_server.go:144 +0x926

The mods this server is launching with are: 
vtk-deep-core-mining_1.11.3.zip
rso-mod_3.5.9.zip
Geothermal_1.0.72.zip
Bio_Industries_2.2.0.zip
Big_Brother_0.4.6.zip
alien-biomes_0.3.8.zip

Also I noticed that the update in server manager still downgrades mods.

**Comment by knoxfighter** [comment]
> Also I noticed that the update in server manager still downgrades mods.

Thats correct, my bugfixes arent pushed in a new Release, so the current Release 0.7.1 has those bugs.
When you download the newest commit and compile/build it yourself, the downgrading mods issue should be solved.

**Comment by mroote** [comment]
Hi @Seorii are you still running into that error with the new version?

**Comment by knoxfighter** [comment]
Closed due to age. If the error persist, please reopen this issue or create a new one.
