### ISSUE TITLE
unable to start server

### ISSUE THREAD

**Issue by BBoSec** [mroote/factorio-server-manager#99]
Hi,

I'm unable to start the factorio server.

I'm calling the factorio server manager with:

./factorio-server-manager --dir /home/factorio/factorio --port 18080
2018/03/29 17:48:06 no mods dir found ... creating one ...
2018/03/29 17:48:06 no ModPackDir found ... creating one ...
2018/03/29 17:48:06 found old modpack files, rebuild into new system...
2018/03/29 17:48:06 all modPacks are loaded into the new system successfully
2018/03/29 17:48:06 deleting old modPackDir
2018/03/29 17:48:06 Loaded Factorio settings from /home/factorio/factorio/config/server-settings.json
2018/03/29 17:48:06 Created/Updated user: admin
2018/03/29 17:48:06 Starting server on: 0.0.0.0:18080

Now I can login to the webinterface, upload an savegame (yes current version) and press the green start button.

If I understand the log correctly, the factorio server has no IP to be binded to.

Here the log.

2018/03/29 17:52:04 Starting Factorio server.
2018/03/29 17:52:04 Starting Factorio server with settings: {"savefile":"Trainstation-0.16.X.zip","port":34197}
2018/03/29 17:52:04 Starting server with command:  /home/factorio/factorio/bin/x64/factorio [--bind  --port 34197 --server-settings /home/factorio/factorio/config/server-settings.json --rcon-port 43081 --rcon-password factorio_rcon --start-server /home/factorio/factorio/saves/Trainstation-0.16.X.zip]
2018/03/29 17:52:04 Factorio Server:    0.000  Current open file limits: 1024, 1048576
2018/03/29 17:52:04 Factorio Server:    0.000  Setting open file limits: 1024, 1048576
2018/03/29 17:52:04 Factorio Server:    0.000 2018-03-29 17:52:04; Factorio 0.16.35 (build 36215, linux64, headless)
2018/03/29 17:52:05 Factorio Server:    0.097 Operating system: Linux (Debian 9.3)
2018/03/29 17:52:05 Factorio Server:    0.097 Program arguments: "/home/factorio/factorio/bin/x64/factorio" "--bind" "" "--port" "34197" "--server-settings" "/home/factorio/factorio/config/server-settings.json" "--rcon-port" "43081" "--rcon-password" <private> "--start-server" "/home/factorio/factorio/saves/Trainstation-0.16.X.zip"
2018/03/29 17:52:05 Factorio Server:    0.097 Read data path: /home/factorio/factorio/data
2018/03/29 17:52:05 Factorio Server:    0.097 Write data path: /home/factorio/factorio [245614/468359MB]
2018/03/29 17:52:05 Factorio Server:    0.097 Binaries path: /home/factorio/factorio/bin
2018/03/29 17:52:05 Factorio Server:    0.115 System info: [CPU: AMD Athlon(tm) Dual Core Processor 4850e, 2 cores, RAM: 3711 MB]
2018/03/29 17:52:05 Factorio Server:    0.115 Environment: DISPLAY=<unset>, WAYLAND_DISPLAY=<unset>
2018/03/29 17:52:05 Factorio Server:    0.116 Running in headless mode
2018/03/29 17:52:05 Factorio Server:    0.120 Error GlobalModSettings.cpp:107: Failed to migrate mod settings file: Error when opening /home/factorio/factorio/mods/mod-settings.json for reading: No such file or directory
2018/03/29 17:52:05 [0.120 Error GlobalModSettings.cpp:107: Failed to migrate mod settings file: Error when opening /home/factorio/factorio/mods/mod-settings.json for reading: No such file or directory]
2018/03/29 17:52:05 Factorio Server:    0.122 Loading mod core 0.0.0 (data.lua)
2018/03/29 17:52:05 Factorio Server:    0.145 Loading mod base 0.16.35 (data.lua)
2018/03/29 17:52:05 Factorio Server:    0.401 Loading mod base 0.16.35 (data-updates.lua)
2018/03/29 17:52:05 Factorio Server:    0.506 Checksum for core: 1316978547
2018/03/29 17:52:05 Factorio Server:    0.506 Checksum of base: 4140083139
2018/03/29 17:52:05 Factorio Server:    0.783 Info PlayerData.cpp:65: Local player-data.json available, timestamp 1522345795
2018/03/29 17:52:05 Factorio Server:    0.783 Info PlayerData.cpp:72: Cloud player-data.json unavailable
2018/03/29 17:52:05 Factorio Server:    0.785 Custom inputs active: 0
2018/03/29 17:52:05 Factorio Server:    0.786 Factorio initialised
2018/03/29 17:52:05 Factorio Server:    0.788 Info GlobalContext.cpp:694: Waiting for child processes to exit:
2018/03/29 17:52:05 Factorio Server:    0.789 Info ServerMultiplayerManager.cpp:142: Quitting multiplayer connection.
2018/03/29 17:52:05 Factorio Server:    0.789 Info ServerMultiplayerManager.cpp:698: mapTick(4294967295) changing state from(Ready) to(Closed)
2018/03/29 17:52:05 Factorio Server:    0.816 Goodbye
2018/03/29 17:52:05 Factorio Server:    0.000  Error Util.cpp:49: multiplayer.invalid-address("", "Name or service not known")
2018/03/29 17:52:05 [0.000 Error Util.cpp:49: multiplayer.invalid-address("", "Name or service not known")]
2018/03/29 17:52:05 Factorio process exited with error: exit status 1
2018/03/29 17:52:05 Error starting Factorio server: exit status 1
2018/03/29 17:52:05 Did not detect running Factorio server attempt: 0
2018/03/29 17:52:06 Did not detect running Factorio server attempt: 1
2018/03/29 17:52:07 Did not detect running Factorio server attempt: 2
2018/03/29 17:52:08 Did not detect running Factorio server attempt: 3
2018/03/29 17:52:08 Error starting Factorio server: exit status 1

But I can start the server with:
/home/factorio/factorio/bin/x64/factorio --bind 0.0.0.0  --port 34197 --server-settings /home/factorio/factorio/config/server-settings.json --rcon-port 43081 --rcon-password factorio_rcon --start-server home/factorio/factorio/saves/Trainstation-0.16.X.zip

**Comment by knoxfighter** [comment]
It is not possible for me to get the IP empty :(
What i noticed is, that it is possible to define an Ip-Adress und Advanced in the Server Control. There you also can change the Port, where factorio runs on.
When this doesn't help, i don't know what the server is doing to you.

**Comment by BBoSec** [comment]
OK - I found the issue: Browser Caching for older version :-(.

2018/03/30 07:25:53 Starting Factorio server.
2018/03/30 07:25:53 Starting Factorio server with settings: {"bindip":"0.0.0.0","savefile":"_autosave1.zip","port":34197}
2018/03/30 07:25:53 Starting server with command:  /home/factorio/factorio/bin/x64/factorio [--bind 0.0.0.0 --port 34197 --server-settings /home/factorio/factorio/config/server-settings.json --rcon-port 43081 --rcon-password factorio_rcon --start-server /home/factorio/factorio/saves/_autosave1.zip]
2018/03/30 07:25:53 Factorio Server:    0.000 2018-03-30 07:25:53; Factorio 0.16.36 (build 36253, linux64, headless)
2018/03/30 07:25:53 Factorio Server:    0.098 Operating system: Linux (Debian 9.3)
2018/03/30 07:25:53 Factorio Server:    0.098 Program arguments: "/home/factorio/factorio/bin/x64/factorio" "--bind" "0.0.0.0" "--port" "34197" "--server-settings" "/home/factorio/factorio/config/server-settings.json" "--rcon-port" "43081" "--rcon-password" <private> "--start-server" "/home/factorio/factorio/saves/_autosave1.zip"
2018/03/30 07:25:53 Factorio Server:    0.098 Read data path: /home/factorio/factorio/data
2018/03/30 07:25:53 Factorio Server:    0.098 Write data path: /home/factorio/factorio [245526/468359MB]
2018/03/30 07:25:53 Factorio Server:    0.098 Binaries path: /home/factorio/factorio/bin
2018/03/30 07:25:53 Factorio Server:    0.116 System info: [CPU: AMD Athlon(tm) Dual Core Processor 4850e, 2 cores, RAM: 3711 MB]
2018/03/30 07:25:53 Factorio Server:    0.116 Environment: DISPLAY=<unset>, WAYLAND_DISPLAY=<unset>
2018/03/30 07:25:53 Factorio Server:    0.116 Running in headless mode
2018/03/30 07:25:53 Factorio Server:    0.120 Error GlobalModSettings.cpp:107: Failed to migrate mod settings file: Error when opening /home/factorio/factorio/mods/mod-settings.json for reading: No such file or directory
2018/03/30 07:25:53 [0.120 Error GlobalModSettings.cpp:107: Failed to migrate mod settings file: Error when opening /home/factorio/factorio/mods/mod-settings.json for reading: No such file or directory]
2018/03/30 07:25:53 Factorio Server:    0.122 Loading mod core 0.0.0 (data.lua)
2018/03/30 07:25:53 Factorio Server:    0.146 Loading mod base 0.16.36 (data.lua)
2018/03/30 07:25:53 Factorio Server:    0.399 Loading mod base 0.16.36 (data-updates.lua)
2018/03/30 07:25:53 Factorio Server:    0.499 Checksum for core: 1316978547
2018/03/30 07:25:53 Factorio Server:    0.499 Checksum of base: 4140083139
2018/03/30 07:25:54 Factorio Server:    0.785 Info PlayerData.cpp:65: Local player-data.json available, timestamp 1522394556
2018/03/30 07:25:54 Factorio Server:    0.785 Info PlayerData.cpp:72: Cloud player-data.json unavailable
2018/03/30 07:25:54 Factorio Server:    0.787 Custom inputs active: 0
2018/03/30 07:25:54 Factorio Server:    0.787 Factorio initialised
2018/03/30 07:25:54 Factorio Server:    0.790 Info ServerSynchronizer.cpp:29: nextHeartbeatSequenceNumber(0) initialized Synchronizer nextTickClosureTick(0).
2018/03/30 07:25:54 Factorio Server:    0.790 Info ServerMultiplayerManager.cpp:698: mapTick(4294967295) changing state from(Ready) to(PreparedToHostGame)
2018/03/30 07:25:54 Factorio Server:    0.790 Info ServerMultiplayerManager.cpp:698: mapTick(4294967295) changing state from(PreparedToHostGame) to(CreatingGame)
2018/03/30 07:25:54 Factorio Server:    0.790 Loading map /home/factorio/factorio/saves/_autosave1.zip: 11393417 bytes.
2018/03/30 07:25:54 Factorio Server:    0.886 Loading Level.dat: 5310906 bytes.
2018/03/30 07:25:54 Factorio Server:    0.902 Info Scenario.cpp:136: Map version 0.16.36-2
2018/03/30 07:25:54 Factorio server started on port: 34197
2018/03/30 07:25:54 Factorio Server:    1.289 Loading script.dat: 175 bytes.
2018/03/30 07:25:54 Factorio Server:    1.293 Checksum for script /home/factorio/factorio/temp/currently-playing/control.lua: 55817070
2018/03/30 07:25:54 Factorio Server:    1.304 Info UDPSocket.cpp:27: Opening socket at (766b2b862614b8b6cd153b0630853c757dd64c6f)
2018/03/30 07:25:54 Factorio Server:    1.304 Hosting game at 766b2b862614b8b6cd153b0630853c757dd64c6f
2018/03/30 07:25:54 Factorio Server:    1.304 Info HttpSharedState.cpp:54: Downloading https://auth.factorio.com/generate-server-padlock-2
2018/03/30 07:25:55 Factorio Server:    1.773 Info HttpSharedState.cpp:145: Status code: 200
2018/03/30 07:25:55 Factorio Server:    1.774 Info AuthServerConnector.cpp:109: Obtained serverPadlock for serverHash (WfM8JsVn7dcoC9BNd8wWtFHcWKiJIF2u) from the auth server.
2018/03/30 07:25:55 Factorio Server:    1.774 Info ServerMultiplayerManager.cpp:698: mapTick(216001) changing state from(CreatingGame) to(InGame)
2018/03/30 07:25:55 Factorio Server:    1.774 Info ServerRouter.cpp:596: Asking pingpong servers (pingpong1.factorio.com:34197, pingpong2.factorio.com:34197) for own address
2018/03/30 07:25:55 Factorio Server:    1.777 Info UDPSocket.cpp:39: Opening socket for broadcast
2018/03/30 07:25:55 Factorio Server:    1.798 Info RemoteCommandProcessor.cpp:128: Starting RCON interface at port 43081
2018/03/30 07:25:55 Rcon running on Factorio Server
2018/03/30 07:25:55 rcon session established on 127.0.0.1:43081
2018/03/30 07:25:55 Factorio Server:    1.799 Info RemoteCommandProcessor.cpp:235: New RCON connection from 789c72c80b7cae63556bbf9ce33254b4ffd13d7b
2018/03/30 07:25:55 Factorio Server:    1.818 Info ServerRouter.cpp:491: Own address is 8b4eaa41486135ab11bc26c049f356a81926c147
2018/03/30 07:25:55 Factorio Server:    1.818 Error ServerMultiplayerManager.cpp:632: Matching server connection failed: Error when creating server game: Missing token.
2018/03/30 07:25:55 [1.818 Error ServerMultiplayerManager.cpp:632: Matching server connection failed: Error when creating server game: Missing token.]


you can close this issue.

**Comment by mroote** [comment]
Glad you found the issue!
